### ISSUE TITLE
Kanban Board Project Setup

### ISSUE THREAD

**Issue by Lembani** [Lembani/catalog-of-my-things#34]
### This issue contains the setup of the Kanban board of our Group Capstone project.

Our Team has 2 members:
- Team Member 1: @christianbiring1 
- Team Member 2: @Lembani 

Link to project board: https://github.com/Lembani/catalog-of-my-things/projects/1

**Comment by thecodechaser** [comment]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Lembani, and @christianbiring1👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️

- [ ] In your task cards please replace `X` in [Xpt] with a number that number should indicate the number of points that show how complex the task is. Hint: [1pt] 1 point = 1 hour of estimated work. (time estimate distributions should be fair).
- [ ] Please add a descriptive title for every task card.

Take a look at this task card for a hint:
![image](https://user-images.githubusercontent.com/83803414/182348267-b48471b7-e19b-4b7c-966b-94c3f23d2044.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Lembani** [comment]
Thanks @thecodechaser for the feedback. We will fix the issues right away.

**Comment by Lordkaito** [comment]
Hi @Lembani, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Lembani** [comment]
Hi @Lordkaito, thanks for approving our PR. 🙏🏾
